// AUTO-GENERATED by scripts/gen_types.py — 请勿手改。
// 源:FastAPI OpenAPI(Pydantic 响应/请求模型)。后端改模型后重跑 `python scripts/gen_types.py`。

export interface ByModelEntryResponse {
  model: string;
  input_tokens: number;
  output_tokens: number;
  cache_n: number;
  request_count: number;
  hit_rate: number;
  share: number;
  latency_ms: number;
}

export interface ClaudeApplyRequest {
  name: string;
}

export interface ClaudeConfigsUpdate {
  configs: Record<string, Record<string, string>>;
}

export interface CommandInput {
  exe: string;
  args?: string[];
  env?: Record<string, string>;
  cwd?: string | null;
  conda_env?: string | null;
}

export interface CostByModelResponse {
  model: string;
  pricing_type: string;
  cost: number;
}

export interface CostSummaryResponse {
  total_cost: number;
  by_model: CostByModelResponse[];
}

export interface LogLineResponse {
  id: number;
  ts: number;
  stream: string;
  level: string;
  text: string;
}

export interface LogRetentionUpdate {
  days?: number | null;
  count?: number | null;
}

export interface LogSearchMatch {
  session_id: number;
  line: LogLineResponse;
}

export interface LogSearchResponse {
  total: number;
  matches: LogSearchMatch[];
}

export interface LogSessionResponse {
  id: number;
  type: string;
  model_name: string | null;
  alias: string | null;
  start_time: number;
  end_time: number | null;
  status: string;
  duration_s: number | null;
  line_count: number;
}

export interface ModelDefInput {
  name: string;
  mode: string;
  port: number;
  auto_start?: boolean;
  aliases: string[];
  schemes: SchemeInput[];
  pricing?: PricingInput;
}

export interface PricingInput {
  pricing_type?: "tier" | "hourly";
  hourly_price?: number;
  support_cache?: boolean;
  tiers?: PricingTierInput[];
}

export interface PricingTierInput {
  tier_index: number;
  min_input?: number | null;
  max_input?: number | null;
  min_output?: number | null;
  max_output?: number | null;
  input_price?: number;
  output_price?: number;
  cache_write_price?: number;
  cache_read_price?: number;
}

export interface ProgramUpdate {
  host?: string | null;
  port?: number | null;
  alive_time?: number | null;
  log_level?: string | null;
  claude_settings_path?: string | null;
}

export interface SchemeInput {
  config_source: string;
  required_devices?: string[];
  command: CommandInput;
  memory_mb?: Record<string, number>;
}

export interface SessionUsageResponse {
  started_at: number;
  input_tokens: number;
  output_tokens: number;
  cache_hit: number;
  cache_miss: number;
  hit_rate: number;
}

export interface UsageSeriesResponse {
  buckets: number[];
  total: number[];
  models: Record<string, number[]>;
}

export interface UsageSummaryResponse {
  input_tokens: number;
  output_tokens: number;
  cache_hit: number;
  cache_miss: number;
  hit_rate: number;
  request_count: number;
}

export interface WolUpdate {
  broadcast_address: string;
  mac_address: string;
}

