"""从 FastAPI OpenAPI 生成 TypeScript 类型(frontend/src/lib/api/schema.d.ts)。

S2(前后端类型对齐):后端 Pydantic 响应/请求模型即唯一真相,前端不再手写同形
interface(防「改后端忘改前端」漂移——正是 log_level 那类坑的根源)。仅生成
components.schemas 命名类型;返回裸 dict 的端点(config/models GET 等)无 schema,
需后端补 response_model 后才会出现(见 AGENTS.md §9 渐进迁移说明)。

自包含、无 npm 依赖:openapi-typescript 官方只支持 TS 5(本项目用 TS 6),且项目
须离线;此脚本纯 stdlib,任何 TS 版本可用,生成结果签入仓库。

用法:python scripts/gen_types.py(后端改响应模型后重跑)。
"""
from __future__ import annotations

import json
import logging
from pathlib import Path

# 静默 create_app 的启动日志,保持生成输出干净。
logging.disable(logging.CRITICAL)

# FastAPI 自动生成的 422 校验错误模型——前端用 parseApiError 解析,不消费这些类型。
_SKIP = {"HTTPValidationError", "ValidationError"}


def main() -> None:
    from llm_manager.app import create_app
    schemas = create_app().openapi().get("components", {}).get("schemas", {})
    out = [
        "// AUTO-GENERATED by scripts/gen_types.py — 请勿手改。",
        "// 源:FastAPI OpenAPI(Pydantic 响应/请求模型)。后端改模型后重跑 `python scripts/gen_types.py`。",
        "",
    ]
    for name in sorted(schemas):
        if name in _SKIP:
            continue
        out.append(_render(name, schemas[name]))
    target = Path(__file__).resolve().parent.parent / "frontend" / "src" / "lib" / "api" / "schema.d.ts"
    target.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {target} ({sum(1 for n in schemas if n not in _SKIP)} schemas)")


def _render(name: str, schema: dict) -> str:
    # 顶层枚举(罕见,Pydantic Literal 顶层):直接 type 别名。
    if "enum" in schema and "properties" not in schema:
        union = " | ".join(json.dumps(v, ensure_ascii=False) for v in schema["enum"])
        return f"export type {name} = {union};\n"
    props = schema.get("properties")
    if not props:
        return f"export type {name} = {_type_of(schema)};\n"
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for prop, sub in props.items():
        opt = "" if prop in required else "?"   # 有默认值的字段不在 required → 可选
        lines.append(f"  {prop}{opt}: {_type_of(sub)};")
    lines.append("}\n")
    return "\n".join(lines)


def _type_of(s: dict) -> str:
    if "$ref" in s:
        return s["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in s:
        return " | ".join(_type_of(x) for x in s["anyOf"])
    if "oneOf" in s:
        return " | ".join(_type_of(x) for x in s["oneOf"])
    if "enum" in s:
        return " | ".join(json.dumps(v, ensure_ascii=False) for v in s["enum"])
    t = s.get("type")
    if t == "array":
        return f"{_type_of(s.get('items', {}))}[]"
    if t == "object":
        if "properties" in s:
            inner = "; ".join(f"{k}: {_type_of(v)}" for k, v in s["properties"].items())
            return f"{{ {inner} }}"
        ap = s.get("additionalProperties")
        if isinstance(ap, dict):
            return f"Record<string, {_type_of(ap)}>"
        return "Record<string, unknown>"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "string":
        return "string"
    if t == "null":
        return "null"
    return "unknown"


if __name__ == "__main__":
    main()
